name: Deploy Lambda with Terraform

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Check TFE_TOKEN available
        run: |
          if [ -z "${{ secrets.TFC_TOKEN }}" ]; then
            echo "❌ TFC_TOKEN is NOT set."
            exit 1
          else
            echo "✅ TFC_TOKEN is set."
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Terraform Init
        run: terraform init
        env:
          TFE_TOKEN: ${{ secrets.TFC_TOKEN }}

      - name: Terraform Apply
        env:
          TFE_TOKEN: ${{ secrets.TFC_TOKEN }}
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_PROJECT: ${{ secrets.PROJECT }}
          TF_VAR_ENV: ${{ secrets.ENV }}
          TF_VAR_SECRET_MANAGER_NAME: ${{ secrets.SECRET_MANAGER_NAME }}
          TF_VAR_LAMBDA_ROLE: ${{ secrets.LAMBDA_ROLE }}
        run: terraform apply -auto-approve